In [1]:
from datetime import datetime
from numba import cuda

In [1]:

now = datetime.now()
 
print("now date and time : " + str(now))
# print("now year : " + str(now.year))
# print("now month : " + str(now.month))
# print("now day : " + str(now.day))
# print("now hour : " + str(now.hour))
# print("now min : " + str(now.minute))
# print("now second : " + str(now.second))
# print("now date : {}-{}-{}".format(now.year, now.month, now.day))


now date and time : 2020-09-19 08:49:00.334032


In [3]:
run hello.py

hello world


In [4]:
run resnet101.py

2.1.0
save/keras/mnist_resnet101_model.h5
5
<class 'tuple'>
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 1 0 0 0 0]
<class 'numpy.ndarray'>
(60000, 28, 28)
===
<class 'numpy.ndarray'>
(60000, 28, 28, 3)
===
(60000,)
Model: "resnet101"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 28, 28, 3)]  0                                            
__________________________________________________________________________________________________
up_sampling2d (UpSampling2D)    (None, 224, 224, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           up_sampling2d[0][0]              
__________________________________________________________________________

In [5]:
cuda.select_device(0)
cuda.close()

In [11]:
now1 = datetime.now()
print("now date and time : " + str(now1))

now date and time : 2020-09-19 10:39:34.551564


In [1]:
run resnet101v2.py

2.1.0
save/keras/mnist_resnet101v2_model.h5
5
<class 'tuple'>
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 1 0 0 0 0]
<class 'numpy.ndarray'>
(60000, 28, 28)
===
<class 'numpy.ndarray'>
(60000, 28, 28, 3)
===
(60000,)
Model: "resnet101v2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 28, 28, 3)]  0                                            
__________________________________________________________________________________________________
up_sampling2d (UpSampling2D)    (None, 224, 224, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           up_sampling2d[0][0]              
______________________________________________________________________

In [6]:
cuda.select_device(0)
cuda.close()

In [7]:
now2 = datetime.now()
print("now date and time : " + str(now2))

now date and time : 2020-09-19 14:26:13.156100


In [1]:
run resnet152.py

2.1.0
save/keras/mnist_resnet152_model.h5
5
<class 'tuple'>
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 1 0 0 0 0]
<class 'numpy.ndarray'>
(60000, 28, 28)
===
<class 'numpy.ndarray'>
(60000, 28, 28, 3)
===
(60000,)
Model: "resnet152"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 28, 28, 3)]  0                                            
__________________________________________________________________________________________________
up_sampling2d (UpSampling2D)    (None, 224, 224, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           up_sampling2d[0][0]              
__________________________________________________________________________

ResourceExhaustedError:  OOM when allocating tensor with shape[32,2048,7,7] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node Conv2DBackpropInput_2 (defined at C:\Users\wlgns\Documents\GitHub\Tensorflow-keras_MNIST\TF\resnet152.py:132) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_distributed_function_56925]

Function call stack:
distributed_function


In [ ]:
cuda.select_device(0)
cuda.close()

In [2]:
now3 = datetime.now()
print("now date and time : " + str(now3))

now date and time : 2020-09-19 14:45:33.510301


In [ ]:
run resnet152v2.py

2.1.0
save/keras/mnist_resnet152v2_model.h5
5
<class 'tuple'>
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 0 0 1 0 0 0 0]
<class 'numpy.ndarray'>
(60000, 28, 28)
===
<class 'numpy.ndarray'>
(60000, 28, 28, 3)
===
(60000,)
Model: "resnet152v2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 28, 28, 3)]  0                                            
__________________________________________________________________________________________________
up_sampling2d (UpSampling2D)    (None, 224, 224, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           up_sampling2d[0][0]              
______________________________________________________________________

In [ ]:
cuda.select_device(0)
cuda.close()

In [ ]:
now4 = datetime.now()
print("now date and time : " + str(now4))

In [ ]:
import pyautogui

In [ ]:
pyautogui.hotkey('ctrl', 's')

In [ ]:
%autosave 60

In [ ]:
import os

In [ ]:
os.system('shutdown -s -t 180')

In [ ]:
# %pip install ipython