# Ch 6. GPU


In [1]:
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='b')
c = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='c')

sess=tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

C:\Users\MBIS\anaconda3\envs\tensorflow114_py37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\MBIS\anaconda3\envs\tensorflow114_py37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\MBIS\anaconda3\envs\tensorflow114_py37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\MBIS\anaconda3\envs\tensorfl

[[1. 2. 3.]
 [4. 5. 6.]]


In [2]:
import tensorflow as tf

with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='b')
    c = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3], name='c')

sess=tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

[[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
import tensorflow as tf

c = []

# for d in ['/gpu:2', '/gpu:3']:
# for d in ['/gpu:0', '/gpu:0']:
#     with tf.device(d):
with tf.device('/gpu:0'):    
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2,3])
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3,2])
    c.append(tf.matmul(a,b))
with tf.device('/cpu:0'):
    sum = tf.add_n(c)
             

sess=tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(sum))

[[22. 28.]
 [49. 64.]]


In [16]:
# gpu example

import numpy as np
import tensorflow as tf
import datetime

A = np.random.rand(1000, 1000).astype('float32')
B = np.random.rand(1000, 1000).astype('float32')

n = 10
c1 = []
c2 = []

In [17]:
def matpow(M, n):
    if n < 1: #Abstract cases where n < 1
        return M
    else:
        return tf.matmul(M, matpow(M, n-1))

In [18]:
with tf.device('/gpu:0'):
    a = tf.constant(A)
    b = tf.constant(B)
    #compute A^n and B^n and store results in c1
    c1.append(matpow(a, n))
    c1.append(matpow(b, n))
    
with tf.device('/cpu:0'):
  sum = tf.add_n(c1) #Addition of all elements in c1, i.e. A^n + B^n


t1_1 = datetime.datetime.now() #################################################################
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    # Runs the op.
    print(sess.run(sum))
t2_1 = datetime.datetime.now() #################################################################

[[9.65223080e+26 9.78540301e+26 9.92698620e+26 ... 9.88771603e+26
  9.68214846e+26 9.71925298e+26]
 [9.66376444e+26 9.78295623e+26 9.93668845e+26 ... 9.89451181e+26
  9.70010526e+26 9.73099544e+26]
 [9.56529055e+26 9.69969501e+26 9.83794081e+26 ... 9.79951624e+26
  9.59383505e+26 9.63168334e+26]
 ...
 [9.59688466e+26 9.72325224e+26 9.86913942e+26 ... 9.82887313e+26
  9.62935536e+26 9.66357333e+26]
 [9.92933779e+26 1.00571280e+27 1.02105739e+27 ... 1.01683146e+27
  9.96427297e+26 9.99836624e+26]
 [9.61368596e+26 9.74310093e+26 9.88685125e+26 ... 9.84708597e+26
  9.64494212e+26 9.68046907e+26]]


In [19]:

print("Single CPU computation time: " + str(t2_1-t1_1))

Single CPU computation time: 0:00:00.864003


In [12]:
%pip install DateTime

Note: you may need to restart the kernel to use updated packages.Installing collected packages: zope.interface, DateTime

